# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDialogAddPropietario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddPropietario(object):
    def setupUi(self, DialogAddPropietario):
        DialogAddPropietario.setObjectName("DialogAddPropietario")
        DialogAddPropietario.resize(324, 133)
        DialogAddPropietario.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(178, 236, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius: 3px;\n"
"    border: 1px solid gray;\n"
"\n"
"}\n"
"QComboBox{\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    min-width: 6em;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(DialogAddPropietario)
        self.label.setGeometry(QtCore.QRect(20, 50, 61, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/recursos/add-user.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.etNombre = QtWidgets.QLineEdit(DialogAddPropietario)
        self.etNombre.setGeometry(QtCore.QRect(100, 50, 191, 20))
        self.etNombre.setObjectName("etNombre")
        self.label_3 = QtWidgets.QLabel(DialogAddPropietario)
        self.label_3.setGeometry(QtCore.QRect(25, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bGuardar = QtWidgets.QPushButton(DialogAddPropietario)
        self.bGuardar.setGeometry(QtCore.QRect(112, 85, 75, 23))
        self.bGuardar.setObjectName("bGuardar")
        self.bCancelar = QtWidgets.QPushButton(DialogAddPropietario)
        self.bCancelar.setGeometry(QtCore.QRect(202, 86, 75, 23))
        self.bCancelar.setObjectName("bCancelar")

        self.retranslateUi(DialogAddPropietario)
        QtCore.QMetaObject.connectSlotsByName(DialogAddPropietario)

    def retranslateUi(self, DialogAddPropietario):
        _translate = QtCore.QCoreApplication.translate
        DialogAddPropietario.setWindowTitle(_translate("DialogAddPropietario", "Nevo Propietario"))
        self.label_3.setText(_translate("DialogAddPropietario", "Indica el nombre del Nuevo Propietario"))
        self.bGuardar.setText(_translate("DialogAddPropietario", "Guardar"))
        self.bCancelar.setText(_translate("DialogAddPropietario", "Cancelar"))
import iconos_rc
